/* Client */
insert into CLIENT (EMAIL, IDENTITY_DOC, IDENTITY_DOC_TYPE_ID, NICKNAME, PHOTO, PASSWORD, COUNTRY_ID, PHONE_NUMBER, ID) values ("email_00000", "identityDoc_0", 11, "nickName_0", "photo_0", "password0", "country0", "phoneNumber0", 1)

/* Natural Person */
insert into NATURAL_PERSON (BIRTHDATE, CELLPHONE_NUMBER, HOME_ADDRESS, LAST_NAME, NAME, PHONE_NUMBER, SECOND_LAST_NAME, ID) values (NULL, "cellphoneNumber_0", "homeAddress_0", "lastName_0", "name_0", "phoneNumber_0", "secondLastName_0", 1)

/* Taxi Caller*/
insert into TAXI_CALLER (REQUEST_DATE, ID_ESTATE, ID_CLIENT, LATITUDE_DESTINY, LATITUDE_ORIGIN, LONGITUDE_DESTINY, LONGITUDE_ORIGIN, ORIGIN_REFERENCES, PAYMENT_TYPE, SERVICE_TYPE) values (SYSDATE() ,"ACT", 1, -11.989951, -11.990834, -77.064780, -77.079639, "CERCA A LA CHOZA NAUTICA", "12345678-9ABC-DEFG-HIJK-LMNOPQRSTUVW", "12345678-9ABC-DEFG-HIJK-LMNOPQRSTUVW")